apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "sentry.fullname" . }}-db-init
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: db-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "sentry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: db-init
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-init
          image: "{{ .Values.images.sentry.repository }}:{{ .Values.images.sentry.tag }}"
          imagePullPolicy: {{ .Values.images.sentry.pullPolicy }}
          command: ["/etc/sentry/entrypoint.sh"]
          args: ["upgrade", "--noinput"]
          env:
            - name: SENTRY_CONF
              value: "/etc/sentry"
            - name: SNUBA
              value: "http://{{ include "sentry.fullname" . }}-snuba-api:1218"
            - name: VROOM
              value: "http://{{ include "sentry.fullname" . }}-vroom:8085"
            - name: SENTRY_SYSTEM_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "sentry.fullname" . }}-secret
                  key: sentry-secret-key
            - name: C_FORCE_ROOT
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/sentry
            - name: geoip
              mountPath: /geoip
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "sentry.fullname" . }}-data
        - name: config
          configMap:
            name: {{ include "sentry.fullname" . }}-config
            defaultMode: 0755
        - name: geoip
          emptyDir: {}
