apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentry.fullname" . }}-memcached
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sentry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: memcached
  template:
    metadata:
      labels:
        {{- include "sentry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: memcached
    spec:
      containers:
        - name: memcached
          image: "{{ .Values.images.memcached.repository }}:{{ .Values.images.memcached.tag }}"
          imagePullPolicy: {{ .Values.images.memcached.pullPolicy }}
          command: ["memcached", "-I", "1M"]
          ports:
            - containerPort: 11211
              name: memcached
          readinessProbe:
            tcpSocket:
              port: 11211
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentry.fullname" . }}-memcached
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  ports:
    - port: 11211
      targetPort: memcached
      name: memcached
  selector:
    {{- include "sentry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
