apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentry.fullname" . }}-postgres
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sentry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "sentry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.images.postgres.repository }}:{{ .Values.images.postgres.tag }}"
          imagePullPolicy: {{ .Values.images.postgres.pullPolicy }}
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
            # Add user/db if needed, defaults are usually postgres/postgres
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              # Use a subPath to avoid unexpected system directories (e.g. lost+found)
              # appearing at the root of the volume. PostgreSQL initialization
              # fails if the data directory is not empty, so mounting a
              # dedicated subdirectory ensures the directory is initially
              # empty and only contains database files.
              subPath: postgres
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "sentry.fullname" . }}-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentry.fullname" . }}-postgres
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "sentry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
