apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentry.fullname" . }}-nginx
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sentry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "sentry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
    spec:
      initContainers:
        - name: download-assets
          image: busybox
          command: ["sh", "-c", "mkdir -p /var/www && wget -q -O /var/www/bundle.min.js https://browser.sentry-cdn.com/7.114.0/bundle.min.js && wget -q -O /var/www/bundle.tracing.min.js https://browser.sentry-cdn.com/7.114.0/bundle.tracing.min.js"] # Update version as needed
          volumeMounts:
            - name: www
              mountPath: /var/www
      containers:
        - name: nginx
          image: "{{ .Values.images.nginx.repository }}:{{ .Values.images.nginx.tag }}"
          imagePullPolicy: {{ .Values.images.nginx.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: cache
              mountPath: /var/cache/nginx
            - name: www
              mountPath: /var/www
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: {{ include "sentry.fullname" . }}-config
        - name: cache
          emptyDir: {}
        - name: www
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentry.fullname" . }}-nginx
  labels:
    {{- include "sentry.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    {{- include "sentry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
